# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = false

[directory]
format = " [$path]($style)[$read_only]($read_only_style) "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = " [\\$](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = " [\\$](bold red)"
vicmd_symbol = " [V](bold green) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true
symbol = " "

[gcloud]
disabled = false
format = '[$symbol$project (\($region\))]($style) '
symbol = " "

[nodejs]
disabled = true

[cmake]
disabled = true

[ruby]
disabled = true

[python]
symbol = " "
style = "blue bold"
format = '[${symbol}${pyenv_prefix}${version}( \($virtualenv\))]($style) '

[php]
format = "[$symbol$version]($style) "
symbol = "PHP "

[golang]
format = "[$symbol $version]($style) "
symbol = "Go"
style = "bold red"
